/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MultiTouch */

#ifndef _Included_MultiTouch
#define _Included_MultiTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MultiTouch
 * Method:    startMultiTouch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MultiTouch_startMultiTouch
  (JNIEnv *, jclass);

/*
 * Class:     MultiTouch
 * Method:    stopMultiTouch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MultiTouch_stopMultiTouch
  (JNIEnv *, jclass);

/*
 * Class:     MultiTouch
 * Method:    registerListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MultiTouch_registerListener
  (JNIEnv *, jclass);

/*
 * Class:     MultiTouch
 * Method:    unregisterListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MultiTouch_unregisterListener
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
