/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mtouch_MultiTouch */

#ifndef _Included_mtouch_MultiTouch
#define _Included_mtouch_MultiTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mtouch_MultiTouch
 * Method:    startMultiTouch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mtouch_MultiTouch_startMultiTouch
  (JNIEnv *, jclass);

/*
 * Class:     mtouch_MultiTouch
 * Method:    stopMultiTouch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mtouch_MultiTouch_stopMultiTouch
  (JNIEnv *, jclass);

/*
 * Class:     mtouch_MultiTouch
 * Method:    registerListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mtouch_MultiTouch_registerListener
  (JNIEnv *, jclass);

/*
 * Class:     mtouch_MultiTouch
 * Method:    unregisterListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mtouch_MultiTouch_unregisterListener
  (JNIEnv *, jclass);

/*
 * Class:     mtouch_MultiTouch
 * Method:    registerObject
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_mtouch_MultiTouch_registerObject
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
